export const mockRatingChartData = [
  { month: "January", NR: 186},
  { month: "February", NR: 177},
  { month: "March", NR: 161},
  { month: "April", NR: 190},
  { month: "May", NR: 154},
]
export const mockUsers = [
  {
    ID: 1,
    CreatedAt: new Date(),
    UpdatedAt: new Date(),
    DeletedAt: null,
    first_name: "Maksim",
    last_name: "Kask",
    birth_date: new Date("1990-06-15"),
    club_id: "Spinmaster",
    email: "max.xd@example.com",
    sex: "M",
    rating_points: 1200,
    placement_points: 30,
    weight_points: 25,
    eltl_id: 101,
    confirmation: "Yes",
    has_rating: true,
    nationality: "Estonian",
    placing_order: 1,
    rank_change: 2,
  },
  {
    ID: 2,
    CreatedAt: new Date(),
    UpdatedAt: new Date(),
    DeletedAt: null,
    first_name: "Linda",
    last_name: "Smith",
    birth_date: new Date("1995-09-21"),
    club_id: "Viimsi LTK",
    email: "linda.smith@example.com",
    sex: "N",
    rating_points: 1150,
    placement_points: 28,
    weight_points: 22,
    eltl_id: 102,
    confirmation: "Yes",
    has_rating: true,
    nationality: "Estonian",
    placing_order: 2,
    rank_change: -1,
  },
  {
    ID: 3,
    CreatedAt: new Date(),
    UpdatedAt: new Date(),
    DeletedAt: null,
    first_name: "Aleks",
    last_name: "Toomso",
    birth_date: new Date("1988-11-03"),
    club_id: "Pärnu Vint-90",
    email: "aleks.toomsoo@example.com",
    sex: "M",
    rating_points: 1100,
    placement_points: 25,
    weight_points: 20,
    eltl_id: 103,
    confirmation: "No",
    has_rating: false,
    nationality: "Estonian",
    placing_order: 3,
    rank_change: 1,
  },
  {
    ID: 4,
    CreatedAt: new Date(),
    UpdatedAt: new Date(),
    DeletedAt: null,
    first_name: "Emily",
    last_name: "Lebotaja",
    birth_date: new Date("1993-05-10"),
    club_id: "Narva LTK",
    email: "emily.lebotaja@example.com",
    sex: "N",
    rating_points: 1080,
    placement_points: 22,
    weight_points: 18,
    eltl_id: 104,
    confirmation: "Yes",
    has_rating: true,
    nationality: "Estonian",
    placing_order: 4,
    rank_change: 0,
  },
  {
    ID: 5,
    CreatedAt: new Date(),
    UpdatedAt: new Date(),
    DeletedAt: null,
    first_name: "Kristjan",
    last_name: "Parna",
    birth_date: new Date("1992-01-12"),
    club_id: "Narova",
    email: "krissu@example.com",
    sex: "M",
    rating_points: 1050,
    placement_points: 20,
    weight_points: 16,
    eltl_id: 105,
    confirmation: "Yes",
    has_rating: false,
    nationality: "Estonian",
    placing_order: 5,
    rank_change: 0,
  },
  {
    ID: 6,
    CreatedAt: new Date(),
    UpdatedAt: new Date(),
    DeletedAt: null,
    first_name: "Anu",
    last_name: "Tamme",
    birth_date: new Date("2010-03-25"), 
    club_id: "Viimsi LTK",
    email: "anu.tamme@example.com",
    sex: "N",
    rating_points: 980,
    placement_points: 18,
    weight_points: 15,
    eltl_id: 106,
    confirmation: "Yes",
    has_rating: true,
    nationality: "Estonian",
    placing_order: 6,
    rank_change: 2,
  },
  {
    ID: 7,
    CreatedAt: new Date(),
    UpdatedAt: new Date(),
    DeletedAt: null,
    first_name: "Martin",
    last_name: "Saar",
    birth_date: new Date("2005-11-18"), 
    club_id: "Pärnu LTK",
    email: "martin.saar@example.com",
    sex: "M",
    rating_points: 1150,
    placement_points: 26,
    weight_points: 22,
    eltl_id: 107,
    confirmation: "Yes",
    has_rating: true,
    nationality: "Estonian",
    placing_order: 7,
    rank_change: 0,
  },
  {
    ID: 8,
    CreatedAt: new Date(),
    UpdatedAt: new Date(),
    DeletedAt: null,
    first_name: "Laura",
    last_name: "Rebane",
    birth_date: new Date("2007-05-22"), 
    club_id: "Tallinna LTK",
    email: "laura.rebane@example.com",
    sex: "N",
    rating_points: 1100,
    placement_points: 22,
    weight_points: 20,
    eltl_id: 108,
    confirmation: "Yes",
    has_rating: false,
    nationality: "Estonian",
    placing_order: 8,
    rank_change: 1,
  },
  {
    ID: 9,
    CreatedAt: new Date(),
    UpdatedAt: new Date(),
    DeletedAt: null,
    first_name: "Toomas",
    last_name: "Leht",
    birth_date: new Date("1982-07-30"), 
    club_id: "Spinmaster",
    email: "toomas.leht@example.com",
    sex: "M",
    rating_points: 1120,
    placement_points: 30,
    weight_points: 26,
    eltl_id: 109,
    confirmation: "Yes",
    has_rating: true,
    nationality: "Estonian",
    placing_order: 9,
    rank_change: -1,
  },
  {
    ID: 10,
    CreatedAt: new Date(),
    UpdatedAt: new Date(),
    DeletedAt: null,
    first_name: "Merike",
    last_name: "Oja",
    birth_date: new Date("1998-09-14"), 
    club_id: "Narva LTK",
    email: "merike.oja@example.com",
    sex: "N",
    rating_points: 1085,
    placement_points: 25,
    weight_points: 21,
    eltl_id: 110,
    confirmation: "Yes",
    has_rating: true,
    nationality: "Estonian",
    placing_order: 10,
    rank_change: 1,
  },
  {
    ID: 11,
    CreatedAt: new Date(),
    UpdatedAt: new Date(),
    DeletedAt: null,
    first_name: "Rasmus",
    last_name: "Laan",
    birth_date: new Date("2006-04-12"), 
    club_id: "Viimsi LTK",
    email: "rasmus.laan@example.com",
    sex: "M",
    rating_points: 1170,
    placement_points: 24,
    weight_points: 22,
    eltl_id: 111,
    confirmation: "Yes",
    has_rating: true,
    nationality: "Estonian",
    placing_order: 11,
    rank_change: 0,
  },
  {
    ID: 12,
    CreatedAt: new Date(),
    UpdatedAt: new Date(),
    DeletedAt: null,
    first_name: "Helena",
    last_name: "Karu",
    birth_date: new Date("2012-01-20"), 
    club_id: "Tallinna Kalev",
    email: "helena.karu@example.com",
    sex: "N",
    rating_points: 940,
    placement_points: 17,
    weight_points: 13,
    eltl_id: 112,
    confirmation: "Yes",
    has_rating: true,
    nationality: "Estonian",
    placing_order: 12,
    rank_change: 0,
  },
  {
    ID: 13,
    CreatedAt: new Date(),
    UpdatedAt: new Date(),
    DeletedAt: null,
    first_name: "Jaanus",
    last_name: "Pärn",
    birth_date: new Date("1985-06-23"), 
    club_id: "Narva LTK",
    email: "jaanus.parn@example.com",
    sex: "M",
    rating_points: 1125,
    placement_points: 28,
    weight_points: 25,
    eltl_id: 113,
    confirmation: "Yes",
    has_rating: true,
    nationality: "Estonian",
    placing_order: 13,
    rank_change: 1,
  },
  {
    ID: 14,
    CreatedAt: new Date(),
    UpdatedAt: new Date(),
    DeletedAt: null,
    first_name: "Maarika",
    last_name: "Rannik",
    birth_date: new Date("1999-08-03"), 
    club_id: "Pärnu Vint-90",
    email: "maarika.rannik@example.com",
    sex: "N",
    rating_points: 1040,
    placement_points: 20,
    weight_points: 18,
    eltl_id: 114,
    confirmation: "Yes",
    has_rating: true,
    nationality: "Estonian",
    placing_order: 14,
    rank_change: 3,
  },
  {
    ID: 15,
    CreatedAt: new Date(),
    UpdatedAt: new Date(),
    DeletedAt: null,
    first_name: "Sander",
    last_name: "Koppel",
    birth_date: new Date("2004-10-09"), 
    club_id: "Spinmaster",
    email: "sander.koppel@example.com",
    sex: "M",
    rating_points: 1140,
    placement_points: 22,
    weight_points: 19,
    eltl_id: 115,
    confirmation: "No",
    has_rating: false,
    nationality: "Estonian",
    placing_order: 15,
    rank_change: 0,
  },
  {
    ID: 16,
    CreatedAt: new Date(),
    UpdatedAt: new Date(),
    DeletedAt: null,
    first_name: "Kadi",
    last_name: "Sepp",
    birth_date: new Date("2011-12-15"), 
    club_id: "Tallinna Kalev",
    email: "kadi.sepp@example.com",
    sex: "N",
    rating_points: 960,
    placement_points: 16,
    weight_points: 14,
    eltl_id: 116,
    confirmation: "Yes",
    has_rating: true,
    nationality: "Estonian",
    placing_order: 16,
    rank_change: -1,
  },
  {
    ID: 17,
    CreatedAt: new Date(),
    UpdatedAt: new Date(),
    DeletedAt: null,
    first_name: "Karl",
    last_name: "Järv",
    birth_date: new Date("1990-03-18"), 
    club_id: "Viimsi LTK",
    email: "karl.jarv@example.com",
    sex: "M",
    rating_points: 1195,
    placement_points: 31,
    weight_points: 27,
    eltl_id: 117,
    confirmation: "Yes",
    has_rating: true,
    nationality: "Estonian",
    placing_order: 17,
    rank_change: 7,
  },
  {
    ID: 18,
    CreatedAt: new Date(),
    UpdatedAt: new Date(),
    DeletedAt: null,
    first_name: "Liisa",
    last_name: "Lind",
    birth_date: new Date("2009-07-04"), 
    club_id: "Narva LTK",
    email: "liisa.lind@example.com",
    sex: "N",
    rating_points: 980,
    placement_points: 19,
    weight_points: 17,
    eltl_id: 118,
    confirmation: "Yes",
    has_rating: false,
    nationality: "Estonian",
    placing_order: 18,
    rank_change: 2,
  },
  {
    ID: 19,
    CreatedAt: new Date(),
    UpdatedAt: new Date(),
    DeletedAt: null,
    first_name: "Eerik",
    last_name: "Tamm",
    birth_date: new Date("1987-02-01"),
    club_id: "Pärnu Vint-90",
    email: "eerik.tamm@example.com",
    sex: "M",
    rating_points: 1105,
    placement_points: 27,
    weight_points: 23,
    eltl_id: 119,
    confirmation: "Yes",
    has_rating: true,
    nationality: "Estonian",
    placing_order: 19,
    rank_change: -2,
  },
  {
    ID: 20,
    CreatedAt: new Date(),
    UpdatedAt: new Date(),
    DeletedAt: null,
    first_name: "Annika",
    last_name: "Vaarik",
    birth_date: new Date("1997-11-19"), 
    club_id: "Spinmaster",
    email: "annika.vaarik@example.com",
    sex: "N",
    rating_points: 1080,
    placement_points: 23,
    weight_points: 20,
    eltl_id: 120,
    confirmation: "No",
    has_rating: false,
    nationality: "Estonian",
    placing_order: 20,
    rank_change: 4,
  },
  {
    ID: 21,
    CreatedAt: new Date(),
    UpdatedAt: new Date(),
    DeletedAt: null,
    first_name: "Oliver",
    last_name: "Karu",
    birth_date: new Date("1980-02-15"),
    club_id: "Spinmaster",
    email: "oliver.karu@example.com",
    sex: "M",
    rating_points: 1250,
    placement_points: 35,
    weight_points: 30,
    eltl_id: 121,
    confirmation: "Yes",
    has_rating: true,
    nationality: "Estonian",
    placing_order: 21,
    rank_change: 1,
  },
  {
    ID: 22,
    CreatedAt: new Date(),
    UpdatedAt: new Date(),
    DeletedAt: null,
    first_name: "Eliise",
    last_name: "Tõrv",
    birth_date: new Date("2008-09-22"),
    club_id: "Tallinna Kalev",
    email: "eliise.torv@example.com",
    sex: "N",
    rating_points: 1020,
    placement_points: 20,
    weight_points: 18,
    eltl_id: 122,
    confirmation: "No",
    has_rating: false,
    nationality: "Estonian",
    placing_order: 22,
    rank_change: 0,
  },
  {
    ID: 23,
    CreatedAt: new Date(),
    UpdatedAt: new Date(),
    DeletedAt: null,
    first_name: "Markus",
    last_name: "Eensalu",
    birth_date: new Date("1995-07-10"),
    club_id: "Viimsi LTK",
    email: "markus.eensalu@example.com",
    sex: "M",
    rating_points: 1180,
    placement_points: 28,
    weight_points: 25,
    eltl_id: 123,
    confirmation: "Yes",
    has_rating: true,
    nationality: "Estonian",
    placing_order: 23,
    rank_change: -1,
  },
  {
    ID: 24,
    CreatedAt: new Date(),
    UpdatedAt: new Date(),
    DeletedAt: null,
    first_name: "Laura",
    last_name: "Kask",
    birth_date: new Date("2013-03-01"),
    club_id: "Narva LTK",
    email: "laura.kask@example.com",
    sex: "N",
    rating_points: 930,
    placement_points: 15,
    weight_points: 12,
    eltl_id: 124,
    confirmation: "Yes",
    has_rating: true,
    nationality: "Estonian",
    placing_order: 24,
    rank_change: 1,
  },
  {
    ID: 25,
    CreatedAt: new Date(),
    UpdatedAt: new Date(),
    DeletedAt: null,
    first_name: "Krista",
    last_name: "Leht",
    birth_date: new Date("1985-05-30"),
    club_id: "Pärnu Vint-90",
    email: "krista.leht@example.com",
    sex: "N",
    rating_points: 1120,
    placement_points: 27,
    weight_points: 24,
    eltl_id: 125,
    confirmation: "Yes",
    has_rating: true,
    nationality: "Estonian",
    placing_order: 25,
    rank_change: -1,
  },
  {
    ID: 26,
    CreatedAt: new Date(),
    UpdatedAt: new Date(),
    DeletedAt: null,
    first_name: "Janek",
    last_name: "Ruut",
    birth_date: new Date("1992-08-18"),
    club_id: "Tallinna Kalev",
    email: "janek.ruut@example.com",
    sex: "M",
    rating_points: 1160,
    placement_points: 30,
    weight_points: 28,
    eltl_id: 126,
    confirmation: "Yes",
    has_rating: true,
    nationality: "Estonian",
    placing_order: 26,
    rank_change: 2,
  },
  {
    ID: 27,
    CreatedAt: new Date(),
    UpdatedAt: new Date(),
    DeletedAt: null,
    first_name: "Mari",
    last_name: "Soo",
    birth_date: new Date("2001-12-02"),
    club_id: "Spinmaster",
    email: "mari.soo@example.com",
    sex: "N",
    rating_points: 1070,
    placement_points: 22,
    weight_points: 18,
    eltl_id: 127,
    confirmation: "No",
    has_rating: false,
    nationality: "Estonian",
    placing_order: 27,
    rank_change: -3,
  },
  {
    ID: 28,
    CreatedAt: new Date(),
    UpdatedAt: new Date(),
    DeletedAt: null,
    first_name: "Oskar",
    last_name: "Laanemets",
    birth_date: new Date("2003-10-11"),
    club_id: "Viimsi LTK",
    email: "oskar.laanemets@example.com",
    sex: "M",
    rating_points: 1140,
    placement_points: 26,
    weight_points: 24,
    eltl_id: 128,
    confirmation: "Yes",
    has_rating: true,
    nationality: "Estonian",
    placing_order: 28,
    rank_change: 1,
  },
  {
    ID: 29,
    CreatedAt: new Date(),
    UpdatedAt: new Date(),
    DeletedAt: null,
    first_name: "Hanna",
    last_name: "Poom",
    birth_date: new Date("2006-05-29"),
    club_id: "Pärnu Vint-90",
    email: "hanna.poom@example.com",
    sex: "N",
    rating_points: 990,
    placement_points: 18,
    weight_points: 16,
    eltl_id: 129,
    confirmation: "No",
    has_rating: false,
    nationality: "Estonian",
    placing_order: 29,
    rank_change: 0,
  },
  {
    ID: 30,
    CreatedAt: new Date(),
    UpdatedAt: new Date(),
    DeletedAt: null,
    first_name: "René",
    last_name: "Vaher",
    birth_date: new Date("1990-01-25"),
    club_id: "Tallinna Kalev",
    email: "rene.vaher@example.com",
    sex: "M",
    rating_points: 1190,
    placement_points: 33,
    weight_points: 30,
    eltl_id: 130,
    confirmation: "Yes",
    has_rating: true,
    nationality: "Estonian",
    placing_order: 30,
    rank_change: 1,
  },
  {
    ID: 31,
    CreatedAt: new Date(),
    UpdatedAt: new Date(),
    DeletedAt: null,
    first_name: "Heidi",
    last_name: "Tamm",
    birth_date: new Date("2010-06-12"),
    club_id: "Narva LTK",
    email: "heidi.tamm@example.com",
    sex: "N",
    rating_points: 950,
    placement_points: 17,
    weight_points: 14,
    eltl_id: 131,
    confirmation: "Yes",
    has_rating: false,
    nationality: "Estonian",
    placing_order: 31,
    rank_change: -1,
  },
  {
    ID: 32,
    CreatedAt: new Date(),
    UpdatedAt: new Date(),
    DeletedAt: null,
    first_name: "Marten",
    last_name: "Kivi",
    birth_date: new Date("1988-04-14"),
    club_id: "Spinmaster",
    email: "marten.kivi@example.com",
    sex: "M",
    rating_points: 1175,
    placement_points: 29,
    weight_points: 26,
    eltl_id: 132,
    confirmation: "Yes",
    has_rating: true,
    nationality: "Estonian",
    placing_order: 32,
    rank_change: 2,
  },
  {
    ID: 33,
    CreatedAt: new Date(),
    UpdatedAt: new Date(),
    DeletedAt: null,
    first_name: "Anneli",
    last_name: "Vares",
    birth_date: new Date("2002-11-23"),
    club_id: "Tallinna LTK",
    email: "anneli.vares@example.com",
    sex: "N",
    rating_points: 1060,
    placement_points: 21,
    weight_points: 19,
    eltl_id: 133,
    confirmation: "No",
    has_rating: false,
    nationality: "Estonian",
    placing_order: 33,
    rank_change: -2,
  },
  {
    ID: 34,
    CreatedAt: new Date(),
    UpdatedAt: new Date(),
    DeletedAt: null,
    first_name: "Karl-Erik",
    last_name: "Põder",
    birth_date: new Date("2007-09-14"),
    club_id: "Viimsi LTK",
    email: "karl-erik.poder@example.com",
    sex: "M",
    rating_points: 1110,
    placement_points: 23,
    weight_points: 20,
    eltl_id: 134,
    confirmation: "Yes",
    has_rating: true,
    nationality: "Estonian",
    placing_order: 34,
    rank_change: 0,
  },
]
