/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AdminLayoutImport } from './routes/admin/layout'
import { Route as IndexImport } from './routes/index'
import { Route as VoistlusedIndexImport } from './routes/voistlused/index'
import { Route as UudisedIndexImport } from './routes/uudised/index'
import { Route as TereIndexImport } from './routes/tere/index'
import { Route as ReitingIndexImport } from './routes/reiting/index'
import { Route as ReeglidIndexImport } from './routes/reeglid/index'
import { Route as LoginIndexImport } from './routes/login/index'
import { Route as KontaktIndexImport } from './routes/kontakt/index'
import { Route as UudisedBlogidImport } from './routes/uudised/$blogid'
import { Route as VoistlusedTournamentidLayoutImport } from './routes/voistlused/$tournamentid/layout'
import { Route as VoistlusedTournamentidIndexImport } from './routes/voistlused/$tournamentid/index'
import { Route as AdminTournamentsIndexImport } from './routes/admin/tournaments/index'
import { Route as AdminDashboardIndexImport } from './routes/admin/dashboard/index'
import { Route as AdminBlogIndexImport } from './routes/admin/blog/index'
import { Route as AdminTournamentsTournamentidLayoutImport } from './routes/admin/tournaments/$tournamentid/layout'
import { Route as VoistlusedTournamentidTulemusedIndexImport } from './routes/voistlused/$tournamentid/tulemused/index'
import { Route as VoistlusedTournamentidSponsoridIndexImport } from './routes/voistlused/$tournamentid/sponsorid/index'
import { Route as VoistlusedTournamentidOsalejadIndexImport } from './routes/voistlused/$tournamentid/osalejad/index'
import { Route as VoistlusedTournamentidMeediaIndexImport } from './routes/voistlused/$tournamentid/meedia/index'
import { Route as VoistlusedTournamentidJuhendIndexImport } from './routes/voistlused/$tournamentid/juhend/index'
import { Route as VoistlusedTournamentidGaleriiIndexImport } from './routes/voistlused/$tournamentid/galerii/index'
import { Route as VoistlusedTournamentidAjakavaIndexImport } from './routes/voistlused/$tournamentid/ajakava/index'
import { Route as AdminTournamentsNewIndexImport } from './routes/admin/tournaments/new/index'
import { Route as AdminTournamentsTournamentidIndexImport } from './routes/admin/tournaments/$tournamentid/index'
import { Route as AdminBlogNewIndexImport } from './routes/admin/blog/new/index'
import { Route as AdminTournamentsTournamentidParticipantsIndexImport } from './routes/admin/tournaments/$tournamentid/participants/index'
import { Route as AdminTournamentsTournamentidMatchesIndexImport } from './routes/admin/tournaments/$tournamentid/matches/index'
import { Route as AdminTournamentsTournamentidGrupidIndexImport } from './routes/admin/tournaments/$tournamentid/grupid/index'
import { Route as AdminTournamentsTournamentidGrupidGroupidLayoutImport } from './routes/admin/tournaments/$tournamentid/grupid/$groupid/layout'
import { Route as AdminTournamentsTournamentidGrupidUusIndexImport } from './routes/admin/tournaments/$tournamentid/grupid/uus/index'
import { Route as AdminTournamentsTournamentidGrupidGroupidIndexImport } from './routes/admin/tournaments/$tournamentid/grupid/$groupid/index'
import { Route as AdminTournamentsTournamentidGrupidGroupidTabelidIndexImport } from './routes/admin/tournaments/$tournamentid/grupid/$groupid/tabelid/index'
import { Route as AdminTournamentsTournamentidGrupidGroupidOsalejadIndexImport } from './routes/admin/tournaments/$tournamentid/grupid/$groupid/osalejad/index'
import { Route as AdminTournamentsTournamentidGrupidGroupidMangudIndexImport } from './routes/admin/tournaments/$tournamentid/grupid/$groupid/mangud/index'

// Create Virtual Routes

const AboutLazyImport = createFileRoute('/about')()

// Create/Update Routes

const AboutLazyRoute = AboutLazyImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/about.lazy').then((d) => d.Route))

const AdminLayoutRoute = AdminLayoutImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const VoistlusedIndexRoute = VoistlusedIndexImport.update({
  id: '/voistlused/',
  path: '/voistlused/',
  getParentRoute: () => rootRoute,
} as any)

const UudisedIndexRoute = UudisedIndexImport.update({
  id: '/uudised/',
  path: '/uudised/',
  getParentRoute: () => rootRoute,
} as any)

const TereIndexRoute = TereIndexImport.update({
  id: '/tere/',
  path: '/tere/',
  getParentRoute: () => rootRoute,
} as any)

const ReitingIndexRoute = ReitingIndexImport.update({
  id: '/reiting/',
  path: '/reiting/',
  getParentRoute: () => rootRoute,
} as any)

const ReeglidIndexRoute = ReeglidIndexImport.update({
  id: '/reeglid/',
  path: '/reeglid/',
  getParentRoute: () => rootRoute,
} as any)

const LoginIndexRoute = LoginIndexImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRoute,
} as any)

const KontaktIndexRoute = KontaktIndexImport.update({
  id: '/kontakt/',
  path: '/kontakt/',
  getParentRoute: () => rootRoute,
} as any)

const UudisedBlogidRoute = UudisedBlogidImport.update({
  id: '/uudised/$blogid',
  path: '/uudised/$blogid',
  getParentRoute: () => rootRoute,
} as any)

const VoistlusedTournamentidLayoutRoute =
  VoistlusedTournamentidLayoutImport.update({
    id: '/voistlused/$tournamentid',
    path: '/voistlused/$tournamentid',
    getParentRoute: () => rootRoute,
  } as any)

const VoistlusedTournamentidIndexRoute =
  VoistlusedTournamentidIndexImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => VoistlusedTournamentidLayoutRoute,
  } as any)

const AdminTournamentsIndexRoute = AdminTournamentsIndexImport.update({
  id: '/tournaments/',
  path: '/tournaments/',
  getParentRoute: () => AdminLayoutRoute,
} as any)

const AdminDashboardIndexRoute = AdminDashboardIndexImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => AdminLayoutRoute,
} as any)

const AdminBlogIndexRoute = AdminBlogIndexImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => AdminLayoutRoute,
} as any)

const AdminTournamentsTournamentidLayoutRoute =
  AdminTournamentsTournamentidLayoutImport.update({
    id: '/tournaments/$tournamentid',
    path: '/tournaments/$tournamentid',
    getParentRoute: () => AdminLayoutRoute,
  } as any)

const VoistlusedTournamentidTulemusedIndexRoute =
  VoistlusedTournamentidTulemusedIndexImport.update({
    id: '/tulemused/',
    path: '/tulemused/',
    getParentRoute: () => VoistlusedTournamentidLayoutRoute,
  } as any)

const VoistlusedTournamentidSponsoridIndexRoute =
  VoistlusedTournamentidSponsoridIndexImport.update({
    id: '/sponsorid/',
    path: '/sponsorid/',
    getParentRoute: () => VoistlusedTournamentidLayoutRoute,
  } as any)

const VoistlusedTournamentidOsalejadIndexRoute =
  VoistlusedTournamentidOsalejadIndexImport.update({
    id: '/osalejad/',
    path: '/osalejad/',
    getParentRoute: () => VoistlusedTournamentidLayoutRoute,
  } as any)

const VoistlusedTournamentidMeediaIndexRoute =
  VoistlusedTournamentidMeediaIndexImport.update({
    id: '/meedia/',
    path: '/meedia/',
    getParentRoute: () => VoistlusedTournamentidLayoutRoute,
  } as any)

const VoistlusedTournamentidJuhendIndexRoute =
  VoistlusedTournamentidJuhendIndexImport.update({
    id: '/juhend/',
    path: '/juhend/',
    getParentRoute: () => VoistlusedTournamentidLayoutRoute,
  } as any)

const VoistlusedTournamentidGaleriiIndexRoute =
  VoistlusedTournamentidGaleriiIndexImport.update({
    id: '/galerii/',
    path: '/galerii/',
    getParentRoute: () => VoistlusedTournamentidLayoutRoute,
  } as any)

const VoistlusedTournamentidAjakavaIndexRoute =
  VoistlusedTournamentidAjakavaIndexImport.update({
    id: '/ajakava/',
    path: '/ajakava/',
    getParentRoute: () => VoistlusedTournamentidLayoutRoute,
  } as any)

const AdminTournamentsNewIndexRoute = AdminTournamentsNewIndexImport.update({
  id: '/tournaments/new/',
  path: '/tournaments/new/',
  getParentRoute: () => AdminLayoutRoute,
} as any)

const AdminTournamentsTournamentidIndexRoute =
  AdminTournamentsTournamentidIndexImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AdminTournamentsTournamentidLayoutRoute,
  } as any)

const AdminBlogNewIndexRoute = AdminBlogNewIndexImport.update({
  id: '/blog/new/',
  path: '/blog/new/',
  getParentRoute: () => AdminLayoutRoute,
} as any)

const AdminTournamentsTournamentidParticipantsIndexRoute =
  AdminTournamentsTournamentidParticipantsIndexImport.update({
    id: '/participants/',
    path: '/participants/',
    getParentRoute: () => AdminTournamentsTournamentidLayoutRoute,
  } as any)

const AdminTournamentsTournamentidMatchesIndexRoute =
  AdminTournamentsTournamentidMatchesIndexImport.update({
    id: '/matches/',
    path: '/matches/',
    getParentRoute: () => AdminTournamentsTournamentidLayoutRoute,
  } as any)

const AdminTournamentsTournamentidGrupidIndexRoute =
  AdminTournamentsTournamentidGrupidIndexImport.update({
    id: '/grupid/',
    path: '/grupid/',
    getParentRoute: () => AdminTournamentsTournamentidLayoutRoute,
  } as any)

const AdminTournamentsTournamentidGrupidGroupidLayoutRoute =
  AdminTournamentsTournamentidGrupidGroupidLayoutImport.update({
    id: '/grupid/$groupid',
    path: '/grupid/$groupid',
    getParentRoute: () => AdminTournamentsTournamentidLayoutRoute,
  } as any)

const AdminTournamentsTournamentidGrupidUusIndexRoute =
  AdminTournamentsTournamentidGrupidUusIndexImport.update({
    id: '/grupid/uus/',
    path: '/grupid/uus/',
    getParentRoute: () => AdminTournamentsTournamentidLayoutRoute,
  } as any)

const AdminTournamentsTournamentidGrupidGroupidIndexRoute =
  AdminTournamentsTournamentidGrupidGroupidIndexImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AdminTournamentsTournamentidGrupidGroupidLayoutRoute,
  } as any)

const AdminTournamentsTournamentidGrupidGroupidTabelidIndexRoute =
  AdminTournamentsTournamentidGrupidGroupidTabelidIndexImport.update({
    id: '/tabelid/',
    path: '/tabelid/',
    getParentRoute: () => AdminTournamentsTournamentidGrupidGroupidLayoutRoute,
  } as any)

const AdminTournamentsTournamentidGrupidGroupidOsalejadIndexRoute =
  AdminTournamentsTournamentidGrupidGroupidOsalejadIndexImport.update({
    id: '/osalejad/',
    path: '/osalejad/',
    getParentRoute: () => AdminTournamentsTournamentidGrupidGroupidLayoutRoute,
  } as any)

const AdminTournamentsTournamentidGrupidGroupidMangudIndexRoute =
  AdminTournamentsTournamentidGrupidGroupidMangudIndexImport.update({
    id: '/mangud/',
    path: '/mangud/',
    getParentRoute: () => AdminTournamentsTournamentidGrupidGroupidLayoutRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminLayoutImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutLazyImport
      parentRoute: typeof rootRoute
    }
    '/voistlused/$tournamentid': {
      id: '/voistlused/$tournamentid'
      path: '/voistlused/$tournamentid'
      fullPath: '/voistlused/$tournamentid'
      preLoaderRoute: typeof VoistlusedTournamentidLayoutImport
      parentRoute: typeof rootRoute
    }
    '/uudised/$blogid': {
      id: '/uudised/$blogid'
      path: '/uudised/$blogid'
      fullPath: '/uudised/$blogid'
      preLoaderRoute: typeof UudisedBlogidImport
      parentRoute: typeof rootRoute
    }
    '/kontakt/': {
      id: '/kontakt/'
      path: '/kontakt'
      fullPath: '/kontakt'
      preLoaderRoute: typeof KontaktIndexImport
      parentRoute: typeof rootRoute
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginIndexImport
      parentRoute: typeof rootRoute
    }
    '/reeglid/': {
      id: '/reeglid/'
      path: '/reeglid'
      fullPath: '/reeglid'
      preLoaderRoute: typeof ReeglidIndexImport
      parentRoute: typeof rootRoute
    }
    '/reiting/': {
      id: '/reiting/'
      path: '/reiting'
      fullPath: '/reiting'
      preLoaderRoute: typeof ReitingIndexImport
      parentRoute: typeof rootRoute
    }
    '/tere/': {
      id: '/tere/'
      path: '/tere'
      fullPath: '/tere'
      preLoaderRoute: typeof TereIndexImport
      parentRoute: typeof rootRoute
    }
    '/uudised/': {
      id: '/uudised/'
      path: '/uudised'
      fullPath: '/uudised'
      preLoaderRoute: typeof UudisedIndexImport
      parentRoute: typeof rootRoute
    }
    '/voistlused/': {
      id: '/voistlused/'
      path: '/voistlused'
      fullPath: '/voistlused'
      preLoaderRoute: typeof VoistlusedIndexImport
      parentRoute: typeof rootRoute
    }
    '/admin/tournaments/$tournamentid': {
      id: '/admin/tournaments/$tournamentid'
      path: '/tournaments/$tournamentid'
      fullPath: '/admin/tournaments/$tournamentid'
      preLoaderRoute: typeof AdminTournamentsTournamentidLayoutImport
      parentRoute: typeof AdminLayoutImport
    }
    '/admin/blog/': {
      id: '/admin/blog/'
      path: '/blog'
      fullPath: '/admin/blog'
      preLoaderRoute: typeof AdminBlogIndexImport
      parentRoute: typeof AdminLayoutImport
    }
    '/admin/dashboard/': {
      id: '/admin/dashboard/'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardIndexImport
      parentRoute: typeof AdminLayoutImport
    }
    '/admin/tournaments/': {
      id: '/admin/tournaments/'
      path: '/tournaments'
      fullPath: '/admin/tournaments'
      preLoaderRoute: typeof AdminTournamentsIndexImport
      parentRoute: typeof AdminLayoutImport
    }
    '/voistlused/$tournamentid/': {
      id: '/voistlused/$tournamentid/'
      path: '/'
      fullPath: '/voistlused/$tournamentid/'
      preLoaderRoute: typeof VoistlusedTournamentidIndexImport
      parentRoute: typeof VoistlusedTournamentidLayoutImport
    }
    '/admin/blog/new/': {
      id: '/admin/blog/new/'
      path: '/blog/new'
      fullPath: '/admin/blog/new'
      preLoaderRoute: typeof AdminBlogNewIndexImport
      parentRoute: typeof AdminLayoutImport
    }
    '/admin/tournaments/$tournamentid/': {
      id: '/admin/tournaments/$tournamentid/'
      path: '/'
      fullPath: '/admin/tournaments/$tournamentid/'
      preLoaderRoute: typeof AdminTournamentsTournamentidIndexImport
      parentRoute: typeof AdminTournamentsTournamentidLayoutImport
    }
    '/admin/tournaments/new/': {
      id: '/admin/tournaments/new/'
      path: '/tournaments/new'
      fullPath: '/admin/tournaments/new'
      preLoaderRoute: typeof AdminTournamentsNewIndexImport
      parentRoute: typeof AdminLayoutImport
    }
    '/voistlused/$tournamentid/ajakava/': {
      id: '/voistlused/$tournamentid/ajakava/'
      path: '/ajakava'
      fullPath: '/voistlused/$tournamentid/ajakava'
      preLoaderRoute: typeof VoistlusedTournamentidAjakavaIndexImport
      parentRoute: typeof VoistlusedTournamentidLayoutImport
    }
    '/voistlused/$tournamentid/galerii/': {
      id: '/voistlused/$tournamentid/galerii/'
      path: '/galerii'
      fullPath: '/voistlused/$tournamentid/galerii'
      preLoaderRoute: typeof VoistlusedTournamentidGaleriiIndexImport
      parentRoute: typeof VoistlusedTournamentidLayoutImport
    }
    '/voistlused/$tournamentid/juhend/': {
      id: '/voistlused/$tournamentid/juhend/'
      path: '/juhend'
      fullPath: '/voistlused/$tournamentid/juhend'
      preLoaderRoute: typeof VoistlusedTournamentidJuhendIndexImport
      parentRoute: typeof VoistlusedTournamentidLayoutImport
    }
    '/voistlused/$tournamentid/meedia/': {
      id: '/voistlused/$tournamentid/meedia/'
      path: '/meedia'
      fullPath: '/voistlused/$tournamentid/meedia'
      preLoaderRoute: typeof VoistlusedTournamentidMeediaIndexImport
      parentRoute: typeof VoistlusedTournamentidLayoutImport
    }
    '/voistlused/$tournamentid/osalejad/': {
      id: '/voistlused/$tournamentid/osalejad/'
      path: '/osalejad'
      fullPath: '/voistlused/$tournamentid/osalejad'
      preLoaderRoute: typeof VoistlusedTournamentidOsalejadIndexImport
      parentRoute: typeof VoistlusedTournamentidLayoutImport
    }
    '/voistlused/$tournamentid/sponsorid/': {
      id: '/voistlused/$tournamentid/sponsorid/'
      path: '/sponsorid'
      fullPath: '/voistlused/$tournamentid/sponsorid'
      preLoaderRoute: typeof VoistlusedTournamentidSponsoridIndexImport
      parentRoute: typeof VoistlusedTournamentidLayoutImport
    }
    '/voistlused/$tournamentid/tulemused/': {
      id: '/voistlused/$tournamentid/tulemused/'
      path: '/tulemused'
      fullPath: '/voistlused/$tournamentid/tulemused'
      preLoaderRoute: typeof VoistlusedTournamentidTulemusedIndexImport
      parentRoute: typeof VoistlusedTournamentidLayoutImport
    }
    '/admin/tournaments/$tournamentid/grupid/$groupid': {
      id: '/admin/tournaments/$tournamentid/grupid/$groupid'
      path: '/grupid/$groupid'
      fullPath: '/admin/tournaments/$tournamentid/grupid/$groupid'
      preLoaderRoute: typeof AdminTournamentsTournamentidGrupidGroupidLayoutImport
      parentRoute: typeof AdminTournamentsTournamentidLayoutImport
    }
    '/admin/tournaments/$tournamentid/grupid/': {
      id: '/admin/tournaments/$tournamentid/grupid/'
      path: '/grupid'
      fullPath: '/admin/tournaments/$tournamentid/grupid'
      preLoaderRoute: typeof AdminTournamentsTournamentidGrupidIndexImport
      parentRoute: typeof AdminTournamentsTournamentidLayoutImport
    }
    '/admin/tournaments/$tournamentid/matches/': {
      id: '/admin/tournaments/$tournamentid/matches/'
      path: '/matches'
      fullPath: '/admin/tournaments/$tournamentid/matches'
      preLoaderRoute: typeof AdminTournamentsTournamentidMatchesIndexImport
      parentRoute: typeof AdminTournamentsTournamentidLayoutImport
    }
    '/admin/tournaments/$tournamentid/participants/': {
      id: '/admin/tournaments/$tournamentid/participants/'
      path: '/participants'
      fullPath: '/admin/tournaments/$tournamentid/participants'
      preLoaderRoute: typeof AdminTournamentsTournamentidParticipantsIndexImport
      parentRoute: typeof AdminTournamentsTournamentidLayoutImport
    }
    '/admin/tournaments/$tournamentid/grupid/$groupid/': {
      id: '/admin/tournaments/$tournamentid/grupid/$groupid/'
      path: '/'
      fullPath: '/admin/tournaments/$tournamentid/grupid/$groupid/'
      preLoaderRoute: typeof AdminTournamentsTournamentidGrupidGroupidIndexImport
      parentRoute: typeof AdminTournamentsTournamentidGrupidGroupidLayoutImport
    }
    '/admin/tournaments/$tournamentid/grupid/uus/': {
      id: '/admin/tournaments/$tournamentid/grupid/uus/'
      path: '/grupid/uus'
      fullPath: '/admin/tournaments/$tournamentid/grupid/uus'
      preLoaderRoute: typeof AdminTournamentsTournamentidGrupidUusIndexImport
      parentRoute: typeof AdminTournamentsTournamentidLayoutImport
    }
    '/admin/tournaments/$tournamentid/grupid/$groupid/mangud/': {
      id: '/admin/tournaments/$tournamentid/grupid/$groupid/mangud/'
      path: '/mangud'
      fullPath: '/admin/tournaments/$tournamentid/grupid/$groupid/mangud'
      preLoaderRoute: typeof AdminTournamentsTournamentidGrupidGroupidMangudIndexImport
      parentRoute: typeof AdminTournamentsTournamentidGrupidGroupidLayoutImport
    }
    '/admin/tournaments/$tournamentid/grupid/$groupid/osalejad/': {
      id: '/admin/tournaments/$tournamentid/grupid/$groupid/osalejad/'
      path: '/osalejad'
      fullPath: '/admin/tournaments/$tournamentid/grupid/$groupid/osalejad'
      preLoaderRoute: typeof AdminTournamentsTournamentidGrupidGroupidOsalejadIndexImport
      parentRoute: typeof AdminTournamentsTournamentidGrupidGroupidLayoutImport
    }
    '/admin/tournaments/$tournamentid/grupid/$groupid/tabelid/': {
      id: '/admin/tournaments/$tournamentid/grupid/$groupid/tabelid/'
      path: '/tabelid'
      fullPath: '/admin/tournaments/$tournamentid/grupid/$groupid/tabelid'
      preLoaderRoute: typeof AdminTournamentsTournamentidGrupidGroupidTabelidIndexImport
      parentRoute: typeof AdminTournamentsTournamentidGrupidGroupidLayoutImport
    }
  }
}

// Create and export the route tree

interface AdminTournamentsTournamentidGrupidGroupidLayoutRouteChildren {
  AdminTournamentsTournamentidGrupidGroupidIndexRoute: typeof AdminTournamentsTournamentidGrupidGroupidIndexRoute
  AdminTournamentsTournamentidGrupidGroupidMangudIndexRoute: typeof AdminTournamentsTournamentidGrupidGroupidMangudIndexRoute
  AdminTournamentsTournamentidGrupidGroupidOsalejadIndexRoute: typeof AdminTournamentsTournamentidGrupidGroupidOsalejadIndexRoute
  AdminTournamentsTournamentidGrupidGroupidTabelidIndexRoute: typeof AdminTournamentsTournamentidGrupidGroupidTabelidIndexRoute
}

const AdminTournamentsTournamentidGrupidGroupidLayoutRouteChildren: AdminTournamentsTournamentidGrupidGroupidLayoutRouteChildren =
  {
    AdminTournamentsTournamentidGrupidGroupidIndexRoute:
      AdminTournamentsTournamentidGrupidGroupidIndexRoute,
    AdminTournamentsTournamentidGrupidGroupidMangudIndexRoute:
      AdminTournamentsTournamentidGrupidGroupidMangudIndexRoute,
    AdminTournamentsTournamentidGrupidGroupidOsalejadIndexRoute:
      AdminTournamentsTournamentidGrupidGroupidOsalejadIndexRoute,
    AdminTournamentsTournamentidGrupidGroupidTabelidIndexRoute:
      AdminTournamentsTournamentidGrupidGroupidTabelidIndexRoute,
  }

const AdminTournamentsTournamentidGrupidGroupidLayoutRouteWithChildren =
  AdminTournamentsTournamentidGrupidGroupidLayoutRoute._addFileChildren(
    AdminTournamentsTournamentidGrupidGroupidLayoutRouteChildren,
  )

interface AdminTournamentsTournamentidLayoutRouteChildren {
  AdminTournamentsTournamentidIndexRoute: typeof AdminTournamentsTournamentidIndexRoute
  AdminTournamentsTournamentidGrupidGroupidLayoutRoute: typeof AdminTournamentsTournamentidGrupidGroupidLayoutRouteWithChildren
  AdminTournamentsTournamentidGrupidIndexRoute: typeof AdminTournamentsTournamentidGrupidIndexRoute
  AdminTournamentsTournamentidMatchesIndexRoute: typeof AdminTournamentsTournamentidMatchesIndexRoute
  AdminTournamentsTournamentidParticipantsIndexRoute: typeof AdminTournamentsTournamentidParticipantsIndexRoute
  AdminTournamentsTournamentidGrupidUusIndexRoute: typeof AdminTournamentsTournamentidGrupidUusIndexRoute
}

const AdminTournamentsTournamentidLayoutRouteChildren: AdminTournamentsTournamentidLayoutRouteChildren =
  {
    AdminTournamentsTournamentidIndexRoute:
      AdminTournamentsTournamentidIndexRoute,
    AdminTournamentsTournamentidGrupidGroupidLayoutRoute:
      AdminTournamentsTournamentidGrupidGroupidLayoutRouteWithChildren,
    AdminTournamentsTournamentidGrupidIndexRoute:
      AdminTournamentsTournamentidGrupidIndexRoute,
    AdminTournamentsTournamentidMatchesIndexRoute:
      AdminTournamentsTournamentidMatchesIndexRoute,
    AdminTournamentsTournamentidParticipantsIndexRoute:
      AdminTournamentsTournamentidParticipantsIndexRoute,
    AdminTournamentsTournamentidGrupidUusIndexRoute:
      AdminTournamentsTournamentidGrupidUusIndexRoute,
  }

const AdminTournamentsTournamentidLayoutRouteWithChildren =
  AdminTournamentsTournamentidLayoutRoute._addFileChildren(
    AdminTournamentsTournamentidLayoutRouteChildren,
  )

interface AdminLayoutRouteChildren {
  AdminTournamentsTournamentidLayoutRoute: typeof AdminTournamentsTournamentidLayoutRouteWithChildren
  AdminBlogIndexRoute: typeof AdminBlogIndexRoute
  AdminDashboardIndexRoute: typeof AdminDashboardIndexRoute
  AdminTournamentsIndexRoute: typeof AdminTournamentsIndexRoute
  AdminBlogNewIndexRoute: typeof AdminBlogNewIndexRoute
  AdminTournamentsNewIndexRoute: typeof AdminTournamentsNewIndexRoute
}

const AdminLayoutRouteChildren: AdminLayoutRouteChildren = {
  AdminTournamentsTournamentidLayoutRoute:
    AdminTournamentsTournamentidLayoutRouteWithChildren,
  AdminBlogIndexRoute: AdminBlogIndexRoute,
  AdminDashboardIndexRoute: AdminDashboardIndexRoute,
  AdminTournamentsIndexRoute: AdminTournamentsIndexRoute,
  AdminBlogNewIndexRoute: AdminBlogNewIndexRoute,
  AdminTournamentsNewIndexRoute: AdminTournamentsNewIndexRoute,
}

const AdminLayoutRouteWithChildren = AdminLayoutRoute._addFileChildren(
  AdminLayoutRouteChildren,
)

interface VoistlusedTournamentidLayoutRouteChildren {
  VoistlusedTournamentidIndexRoute: typeof VoistlusedTournamentidIndexRoute
  VoistlusedTournamentidAjakavaIndexRoute: typeof VoistlusedTournamentidAjakavaIndexRoute
  VoistlusedTournamentidGaleriiIndexRoute: typeof VoistlusedTournamentidGaleriiIndexRoute
  VoistlusedTournamentidJuhendIndexRoute: typeof VoistlusedTournamentidJuhendIndexRoute
  VoistlusedTournamentidMeediaIndexRoute: typeof VoistlusedTournamentidMeediaIndexRoute
  VoistlusedTournamentidOsalejadIndexRoute: typeof VoistlusedTournamentidOsalejadIndexRoute
  VoistlusedTournamentidSponsoridIndexRoute: typeof VoistlusedTournamentidSponsoridIndexRoute
  VoistlusedTournamentidTulemusedIndexRoute: typeof VoistlusedTournamentidTulemusedIndexRoute
}

const VoistlusedTournamentidLayoutRouteChildren: VoistlusedTournamentidLayoutRouteChildren =
  {
    VoistlusedTournamentidIndexRoute: VoistlusedTournamentidIndexRoute,
    VoistlusedTournamentidAjakavaIndexRoute:
      VoistlusedTournamentidAjakavaIndexRoute,
    VoistlusedTournamentidGaleriiIndexRoute:
      VoistlusedTournamentidGaleriiIndexRoute,
    VoistlusedTournamentidJuhendIndexRoute:
      VoistlusedTournamentidJuhendIndexRoute,
    VoistlusedTournamentidMeediaIndexRoute:
      VoistlusedTournamentidMeediaIndexRoute,
    VoistlusedTournamentidOsalejadIndexRoute:
      VoistlusedTournamentidOsalejadIndexRoute,
    VoistlusedTournamentidSponsoridIndexRoute:
      VoistlusedTournamentidSponsoridIndexRoute,
    VoistlusedTournamentidTulemusedIndexRoute:
      VoistlusedTournamentidTulemusedIndexRoute,
  }

const VoistlusedTournamentidLayoutRouteWithChildren =
  VoistlusedTournamentidLayoutRoute._addFileChildren(
    VoistlusedTournamentidLayoutRouteChildren,
  )

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminLayoutRouteWithChildren
  '/about': typeof AboutLazyRoute
  '/voistlused/$tournamentid': typeof VoistlusedTournamentidLayoutRouteWithChildren
  '/uudised/$blogid': typeof UudisedBlogidRoute
  '/kontakt': typeof KontaktIndexRoute
  '/login': typeof LoginIndexRoute
  '/reeglid': typeof ReeglidIndexRoute
  '/reiting': typeof ReitingIndexRoute
  '/tere': typeof TereIndexRoute
  '/uudised': typeof UudisedIndexRoute
  '/voistlused': typeof VoistlusedIndexRoute
  '/admin/tournaments/$tournamentid': typeof AdminTournamentsTournamentidLayoutRouteWithChildren
  '/admin/blog': typeof AdminBlogIndexRoute
  '/admin/dashboard': typeof AdminDashboardIndexRoute
  '/admin/tournaments': typeof AdminTournamentsIndexRoute
  '/voistlused/$tournamentid/': typeof VoistlusedTournamentidIndexRoute
  '/admin/blog/new': typeof AdminBlogNewIndexRoute
  '/admin/tournaments/$tournamentid/': typeof AdminTournamentsTournamentidIndexRoute
  '/admin/tournaments/new': typeof AdminTournamentsNewIndexRoute
  '/voistlused/$tournamentid/ajakava': typeof VoistlusedTournamentidAjakavaIndexRoute
  '/voistlused/$tournamentid/galerii': typeof VoistlusedTournamentidGaleriiIndexRoute
  '/voistlused/$tournamentid/juhend': typeof VoistlusedTournamentidJuhendIndexRoute
  '/voistlused/$tournamentid/meedia': typeof VoistlusedTournamentidMeediaIndexRoute
  '/voistlused/$tournamentid/osalejad': typeof VoistlusedTournamentidOsalejadIndexRoute
  '/voistlused/$tournamentid/sponsorid': typeof VoistlusedTournamentidSponsoridIndexRoute
  '/voistlused/$tournamentid/tulemused': typeof VoistlusedTournamentidTulemusedIndexRoute
  '/admin/tournaments/$tournamentid/grupid/$groupid': typeof AdminTournamentsTournamentidGrupidGroupidLayoutRouteWithChildren
  '/admin/tournaments/$tournamentid/grupid': typeof AdminTournamentsTournamentidGrupidIndexRoute
  '/admin/tournaments/$tournamentid/matches': typeof AdminTournamentsTournamentidMatchesIndexRoute
  '/admin/tournaments/$tournamentid/participants': typeof AdminTournamentsTournamentidParticipantsIndexRoute
  '/admin/tournaments/$tournamentid/grupid/$groupid/': typeof AdminTournamentsTournamentidGrupidGroupidIndexRoute
  '/admin/tournaments/$tournamentid/grupid/uus': typeof AdminTournamentsTournamentidGrupidUusIndexRoute
  '/admin/tournaments/$tournamentid/grupid/$groupid/mangud': typeof AdminTournamentsTournamentidGrupidGroupidMangudIndexRoute
  '/admin/tournaments/$tournamentid/grupid/$groupid/osalejad': typeof AdminTournamentsTournamentidGrupidGroupidOsalejadIndexRoute
  '/admin/tournaments/$tournamentid/grupid/$groupid/tabelid': typeof AdminTournamentsTournamentidGrupidGroupidTabelidIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminLayoutRouteWithChildren
  '/about': typeof AboutLazyRoute
  '/uudised/$blogid': typeof UudisedBlogidRoute
  '/kontakt': typeof KontaktIndexRoute
  '/login': typeof LoginIndexRoute
  '/reeglid': typeof ReeglidIndexRoute
  '/reiting': typeof ReitingIndexRoute
  '/tere': typeof TereIndexRoute
  '/uudised': typeof UudisedIndexRoute
  '/voistlused': typeof VoistlusedIndexRoute
  '/admin/blog': typeof AdminBlogIndexRoute
  '/admin/dashboard': typeof AdminDashboardIndexRoute
  '/admin/tournaments': typeof AdminTournamentsIndexRoute
  '/voistlused/$tournamentid': typeof VoistlusedTournamentidIndexRoute
  '/admin/blog/new': typeof AdminBlogNewIndexRoute
  '/admin/tournaments/$tournamentid': typeof AdminTournamentsTournamentidIndexRoute
  '/admin/tournaments/new': typeof AdminTournamentsNewIndexRoute
  '/voistlused/$tournamentid/ajakava': typeof VoistlusedTournamentidAjakavaIndexRoute
  '/voistlused/$tournamentid/galerii': typeof VoistlusedTournamentidGaleriiIndexRoute
  '/voistlused/$tournamentid/juhend': typeof VoistlusedTournamentidJuhendIndexRoute
  '/voistlused/$tournamentid/meedia': typeof VoistlusedTournamentidMeediaIndexRoute
  '/voistlused/$tournamentid/osalejad': typeof VoistlusedTournamentidOsalejadIndexRoute
  '/voistlused/$tournamentid/sponsorid': typeof VoistlusedTournamentidSponsoridIndexRoute
  '/voistlused/$tournamentid/tulemused': typeof VoistlusedTournamentidTulemusedIndexRoute
  '/admin/tournaments/$tournamentid/grupid': typeof AdminTournamentsTournamentidGrupidIndexRoute
  '/admin/tournaments/$tournamentid/matches': typeof AdminTournamentsTournamentidMatchesIndexRoute
  '/admin/tournaments/$tournamentid/participants': typeof AdminTournamentsTournamentidParticipantsIndexRoute
  '/admin/tournaments/$tournamentid/grupid/$groupid': typeof AdminTournamentsTournamentidGrupidGroupidIndexRoute
  '/admin/tournaments/$tournamentid/grupid/uus': typeof AdminTournamentsTournamentidGrupidUusIndexRoute
  '/admin/tournaments/$tournamentid/grupid/$groupid/mangud': typeof AdminTournamentsTournamentidGrupidGroupidMangudIndexRoute
  '/admin/tournaments/$tournamentid/grupid/$groupid/osalejad': typeof AdminTournamentsTournamentidGrupidGroupidOsalejadIndexRoute
  '/admin/tournaments/$tournamentid/grupid/$groupid/tabelid': typeof AdminTournamentsTournamentidGrupidGroupidTabelidIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/admin': typeof AdminLayoutRouteWithChildren
  '/about': typeof AboutLazyRoute
  '/voistlused/$tournamentid': typeof VoistlusedTournamentidLayoutRouteWithChildren
  '/uudised/$blogid': typeof UudisedBlogidRoute
  '/kontakt/': typeof KontaktIndexRoute
  '/login/': typeof LoginIndexRoute
  '/reeglid/': typeof ReeglidIndexRoute
  '/reiting/': typeof ReitingIndexRoute
  '/tere/': typeof TereIndexRoute
  '/uudised/': typeof UudisedIndexRoute
  '/voistlused/': typeof VoistlusedIndexRoute
  '/admin/tournaments/$tournamentid': typeof AdminTournamentsTournamentidLayoutRouteWithChildren
  '/admin/blog/': typeof AdminBlogIndexRoute
  '/admin/dashboard/': typeof AdminDashboardIndexRoute
  '/admin/tournaments/': typeof AdminTournamentsIndexRoute
  '/voistlused/$tournamentid/': typeof VoistlusedTournamentidIndexRoute
  '/admin/blog/new/': typeof AdminBlogNewIndexRoute
  '/admin/tournaments/$tournamentid/': typeof AdminTournamentsTournamentidIndexRoute
  '/admin/tournaments/new/': typeof AdminTournamentsNewIndexRoute
  '/voistlused/$tournamentid/ajakava/': typeof VoistlusedTournamentidAjakavaIndexRoute
  '/voistlused/$tournamentid/galerii/': typeof VoistlusedTournamentidGaleriiIndexRoute
  '/voistlused/$tournamentid/juhend/': typeof VoistlusedTournamentidJuhendIndexRoute
  '/voistlused/$tournamentid/meedia/': typeof VoistlusedTournamentidMeediaIndexRoute
  '/voistlused/$tournamentid/osalejad/': typeof VoistlusedTournamentidOsalejadIndexRoute
  '/voistlused/$tournamentid/sponsorid/': typeof VoistlusedTournamentidSponsoridIndexRoute
  '/voistlused/$tournamentid/tulemused/': typeof VoistlusedTournamentidTulemusedIndexRoute
  '/admin/tournaments/$tournamentid/grupid/$groupid': typeof AdminTournamentsTournamentidGrupidGroupidLayoutRouteWithChildren
  '/admin/tournaments/$tournamentid/grupid/': typeof AdminTournamentsTournamentidGrupidIndexRoute
  '/admin/tournaments/$tournamentid/matches/': typeof AdminTournamentsTournamentidMatchesIndexRoute
  '/admin/tournaments/$tournamentid/participants/': typeof AdminTournamentsTournamentidParticipantsIndexRoute
  '/admin/tournaments/$tournamentid/grupid/$groupid/': typeof AdminTournamentsTournamentidGrupidGroupidIndexRoute
  '/admin/tournaments/$tournamentid/grupid/uus/': typeof AdminTournamentsTournamentidGrupidUusIndexRoute
  '/admin/tournaments/$tournamentid/grupid/$groupid/mangud/': typeof AdminTournamentsTournamentidGrupidGroupidMangudIndexRoute
  '/admin/tournaments/$tournamentid/grupid/$groupid/osalejad/': typeof AdminTournamentsTournamentidGrupidGroupidOsalejadIndexRoute
  '/admin/tournaments/$tournamentid/grupid/$groupid/tabelid/': typeof AdminTournamentsTournamentidGrupidGroupidTabelidIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/about'
    | '/voistlused/$tournamentid'
    | '/uudised/$blogid'
    | '/kontakt'
    | '/login'
    | '/reeglid'
    | '/reiting'
    | '/tere'
    | '/uudised'
    | '/voistlused'
    | '/admin/tournaments/$tournamentid'
    | '/admin/blog'
    | '/admin/dashboard'
    | '/admin/tournaments'
    | '/voistlused/$tournamentid/'
    | '/admin/blog/new'
    | '/admin/tournaments/$tournamentid/'
    | '/admin/tournaments/new'
    | '/voistlused/$tournamentid/ajakava'
    | '/voistlused/$tournamentid/galerii'
    | '/voistlused/$tournamentid/juhend'
    | '/voistlused/$tournamentid/meedia'
    | '/voistlused/$tournamentid/osalejad'
    | '/voistlused/$tournamentid/sponsorid'
    | '/voistlused/$tournamentid/tulemused'
    | '/admin/tournaments/$tournamentid/grupid/$groupid'
    | '/admin/tournaments/$tournamentid/grupid'
    | '/admin/tournaments/$tournamentid/matches'
    | '/admin/tournaments/$tournamentid/participants'
    | '/admin/tournaments/$tournamentid/grupid/$groupid/'
    | '/admin/tournaments/$tournamentid/grupid/uus'
    | '/admin/tournaments/$tournamentid/grupid/$groupid/mangud'
    | '/admin/tournaments/$tournamentid/grupid/$groupid/osalejad'
    | '/admin/tournaments/$tournamentid/grupid/$groupid/tabelid'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/about'
    | '/uudised/$blogid'
    | '/kontakt'
    | '/login'
    | '/reeglid'
    | '/reiting'
    | '/tere'
    | '/uudised'
    | '/voistlused'
    | '/admin/blog'
    | '/admin/dashboard'
    | '/admin/tournaments'
    | '/voistlused/$tournamentid'
    | '/admin/blog/new'
    | '/admin/tournaments/$tournamentid'
    | '/admin/tournaments/new'
    | '/voistlused/$tournamentid/ajakava'
    | '/voistlused/$tournamentid/galerii'
    | '/voistlused/$tournamentid/juhend'
    | '/voistlused/$tournamentid/meedia'
    | '/voistlused/$tournamentid/osalejad'
    | '/voistlused/$tournamentid/sponsorid'
    | '/voistlused/$tournamentid/tulemused'
    | '/admin/tournaments/$tournamentid/grupid'
    | '/admin/tournaments/$tournamentid/matches'
    | '/admin/tournaments/$tournamentid/participants'
    | '/admin/tournaments/$tournamentid/grupid/$groupid'
    | '/admin/tournaments/$tournamentid/grupid/uus'
    | '/admin/tournaments/$tournamentid/grupid/$groupid/mangud'
    | '/admin/tournaments/$tournamentid/grupid/$groupid/osalejad'
    | '/admin/tournaments/$tournamentid/grupid/$groupid/tabelid'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/about'
    | '/voistlused/$tournamentid'
    | '/uudised/$blogid'
    | '/kontakt/'
    | '/login/'
    | '/reeglid/'
    | '/reiting/'
    | '/tere/'
    | '/uudised/'
    | '/voistlused/'
    | '/admin/tournaments/$tournamentid'
    | '/admin/blog/'
    | '/admin/dashboard/'
    | '/admin/tournaments/'
    | '/voistlused/$tournamentid/'
    | '/admin/blog/new/'
    | '/admin/tournaments/$tournamentid/'
    | '/admin/tournaments/new/'
    | '/voistlused/$tournamentid/ajakava/'
    | '/voistlused/$tournamentid/galerii/'
    | '/voistlused/$tournamentid/juhend/'
    | '/voistlused/$tournamentid/meedia/'
    | '/voistlused/$tournamentid/osalejad/'
    | '/voistlused/$tournamentid/sponsorid/'
    | '/voistlused/$tournamentid/tulemused/'
    | '/admin/tournaments/$tournamentid/grupid/$groupid'
    | '/admin/tournaments/$tournamentid/grupid/'
    | '/admin/tournaments/$tournamentid/matches/'
    | '/admin/tournaments/$tournamentid/participants/'
    | '/admin/tournaments/$tournamentid/grupid/$groupid/'
    | '/admin/tournaments/$tournamentid/grupid/uus/'
    | '/admin/tournaments/$tournamentid/grupid/$groupid/mangud/'
    | '/admin/tournaments/$tournamentid/grupid/$groupid/osalejad/'
    | '/admin/tournaments/$tournamentid/grupid/$groupid/tabelid/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminLayoutRoute: typeof AdminLayoutRouteWithChildren
  AboutLazyRoute: typeof AboutLazyRoute
  VoistlusedTournamentidLayoutRoute: typeof VoistlusedTournamentidLayoutRouteWithChildren
  UudisedBlogidRoute: typeof UudisedBlogidRoute
  KontaktIndexRoute: typeof KontaktIndexRoute
  LoginIndexRoute: typeof LoginIndexRoute
  ReeglidIndexRoute: typeof ReeglidIndexRoute
  ReitingIndexRoute: typeof ReitingIndexRoute
  TereIndexRoute: typeof TereIndexRoute
  UudisedIndexRoute: typeof UudisedIndexRoute
  VoistlusedIndexRoute: typeof VoistlusedIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminLayoutRoute: AdminLayoutRouteWithChildren,
  AboutLazyRoute: AboutLazyRoute,
  VoistlusedTournamentidLayoutRoute:
    VoistlusedTournamentidLayoutRouteWithChildren,
  UudisedBlogidRoute: UudisedBlogidRoute,
  KontaktIndexRoute: KontaktIndexRoute,
  LoginIndexRoute: LoginIndexRoute,
  ReeglidIndexRoute: ReeglidIndexRoute,
  ReitingIndexRoute: ReitingIndexRoute,
  TereIndexRoute: TereIndexRoute,
  UudisedIndexRoute: UudisedIndexRoute,
  VoistlusedIndexRoute: VoistlusedIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/admin",
        "/about",
        "/voistlused/$tournamentid",
        "/uudised/$blogid",
        "/kontakt/",
        "/login/",
        "/reeglid/",
        "/reiting/",
        "/tere/",
        "/uudised/",
        "/voistlused/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/admin": {
      "filePath": "admin/layout.tsx",
      "children": [
        "/admin/tournaments/$tournamentid",
        "/admin/blog/",
        "/admin/dashboard/",
        "/admin/tournaments/",
        "/admin/blog/new/",
        "/admin/tournaments/new/"
      ]
    },
    "/about": {
      "filePath": "about.lazy.tsx"
    },
    "/voistlused/$tournamentid": {
      "filePath": "voistlused/$tournamentid/layout.tsx",
      "children": [
        "/voistlused/$tournamentid/",
        "/voistlused/$tournamentid/ajakava/",
        "/voistlused/$tournamentid/galerii/",
        "/voistlused/$tournamentid/juhend/",
        "/voistlused/$tournamentid/meedia/",
        "/voistlused/$tournamentid/osalejad/",
        "/voistlused/$tournamentid/sponsorid/",
        "/voistlused/$tournamentid/tulemused/"
      ]
    },
    "/uudised/$blogid": {
      "filePath": "uudised/$blogid.tsx"
    },
    "/kontakt/": {
      "filePath": "kontakt/index.tsx"
    },
    "/login/": {
      "filePath": "login/index.tsx"
    },
    "/reeglid/": {
      "filePath": "reeglid/index.tsx"
    },
    "/reiting/": {
      "filePath": "reiting/index.tsx"
    },
    "/tere/": {
      "filePath": "tere/index.tsx"
    },
    "/uudised/": {
      "filePath": "uudised/index.tsx"
    },
    "/voistlused/": {
      "filePath": "voistlused/index.tsx"
    },
    "/admin/tournaments/$tournamentid": {
      "filePath": "admin/tournaments/$tournamentid/layout.tsx",
      "parent": "/admin",
      "children": [
        "/admin/tournaments/$tournamentid/",
        "/admin/tournaments/$tournamentid/grupid/$groupid",
        "/admin/tournaments/$tournamentid/grupid/",
        "/admin/tournaments/$tournamentid/matches/",
        "/admin/tournaments/$tournamentid/participants/",
        "/admin/tournaments/$tournamentid/grupid/uus/"
      ]
    },
    "/admin/blog/": {
      "filePath": "admin/blog/index.tsx",
      "parent": "/admin"
    },
    "/admin/dashboard/": {
      "filePath": "admin/dashboard/index.tsx",
      "parent": "/admin"
    },
    "/admin/tournaments/": {
      "filePath": "admin/tournaments/index.tsx",
      "parent": "/admin"
    },
    "/voistlused/$tournamentid/": {
      "filePath": "voistlused/$tournamentid/index.tsx",
      "parent": "/voistlused/$tournamentid"
    },
    "/admin/blog/new/": {
      "filePath": "admin/blog/new/index.tsx",
      "parent": "/admin"
    },
    "/admin/tournaments/$tournamentid/": {
      "filePath": "admin/tournaments/$tournamentid/index.tsx",
      "parent": "/admin/tournaments/$tournamentid"
    },
    "/admin/tournaments/new/": {
      "filePath": "admin/tournaments/new/index.tsx",
      "parent": "/admin"
    },
    "/voistlused/$tournamentid/ajakava/": {
      "filePath": "voistlused/$tournamentid/ajakava/index.tsx",
      "parent": "/voistlused/$tournamentid"
    },
    "/voistlused/$tournamentid/galerii/": {
      "filePath": "voistlused/$tournamentid/galerii/index.tsx",
      "parent": "/voistlused/$tournamentid"
    },
    "/voistlused/$tournamentid/juhend/": {
      "filePath": "voistlused/$tournamentid/juhend/index.tsx",
      "parent": "/voistlused/$tournamentid"
    },
    "/voistlused/$tournamentid/meedia/": {
      "filePath": "voistlused/$tournamentid/meedia/index.tsx",
      "parent": "/voistlused/$tournamentid"
    },
    "/voistlused/$tournamentid/osalejad/": {
      "filePath": "voistlused/$tournamentid/osalejad/index.tsx",
      "parent": "/voistlused/$tournamentid"
    },
    "/voistlused/$tournamentid/sponsorid/": {
      "filePath": "voistlused/$tournamentid/sponsorid/index.tsx",
      "parent": "/voistlused/$tournamentid"
    },
    "/voistlused/$tournamentid/tulemused/": {
      "filePath": "voistlused/$tournamentid/tulemused/index.tsx",
      "parent": "/voistlused/$tournamentid"
    },
    "/admin/tournaments/$tournamentid/grupid/$groupid": {
      "filePath": "admin/tournaments/$tournamentid/grupid/$groupid/layout.tsx",
      "parent": "/admin/tournaments/$tournamentid",
      "children": [
        "/admin/tournaments/$tournamentid/grupid/$groupid/",
        "/admin/tournaments/$tournamentid/grupid/$groupid/mangud/",
        "/admin/tournaments/$tournamentid/grupid/$groupid/osalejad/",
        "/admin/tournaments/$tournamentid/grupid/$groupid/tabelid/"
      ]
    },
    "/admin/tournaments/$tournamentid/grupid/": {
      "filePath": "admin/tournaments/$tournamentid/grupid/index.tsx",
      "parent": "/admin/tournaments/$tournamentid"
    },
    "/admin/tournaments/$tournamentid/matches/": {
      "filePath": "admin/tournaments/$tournamentid/matches/index.tsx",
      "parent": "/admin/tournaments/$tournamentid"
    },
    "/admin/tournaments/$tournamentid/participants/": {
      "filePath": "admin/tournaments/$tournamentid/participants/index.tsx",
      "parent": "/admin/tournaments/$tournamentid"
    },
    "/admin/tournaments/$tournamentid/grupid/$groupid/": {
      "filePath": "admin/tournaments/$tournamentid/grupid/$groupid/index.tsx",
      "parent": "/admin/tournaments/$tournamentid/grupid/$groupid"
    },
    "/admin/tournaments/$tournamentid/grupid/uus/": {
      "filePath": "admin/tournaments/$tournamentid/grupid/uus/index.tsx",
      "parent": "/admin/tournaments/$tournamentid"
    },
    "/admin/tournaments/$tournamentid/grupid/$groupid/mangud/": {
      "filePath": "admin/tournaments/$tournamentid/grupid/$groupid/mangud/index.tsx",
      "parent": "/admin/tournaments/$tournamentid/grupid/$groupid"
    },
    "/admin/tournaments/$tournamentid/grupid/$groupid/osalejad/": {
      "filePath": "admin/tournaments/$tournamentid/grupid/$groupid/osalejad/index.tsx",
      "parent": "/admin/tournaments/$tournamentid/grupid/$groupid"
    },
    "/admin/tournaments/$tournamentid/grupid/$groupid/tabelid/": {
      "filePath": "admin/tournaments/$tournamentid/grupid/$groupid/tabelid/index.tsx",
      "parent": "/admin/tournaments/$tournamentid/grupid/$groupid"
    }
  }
}
ROUTE_MANIFEST_END */
